# Generated by Django 4.0.4 on 2022-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pri', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
